version: '2'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
        - comment_db
        - post_db

  ui:
    image: tenki/ui:5.0
    ports:
      - 9292:9292/tcp
    networks:
      - frontend
      
  post:
    image: tenki/post:4.0
    networks:
      - frontend
      - backend

  comment:
    image: tenki/comment:4.0
    networks:
      - frontend
      - backend

volumes:
  post_db:

networks:
  backend:
  frontend:
